// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class ProdFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxpruFN46ANBedqqPzJO27BGFB5v083yk',
    appId: '1:467044849667:web:5731e68a7976160dc61636',
    messagingSenderId: '467044849667',
    projectId: 'kagong-release',
    authDomain: 'kagong-release.firebaseapp.com',
    storageBucket: 'kagong-release.firebasestorage.app',
    measurementId: 'G-G07V55MFVN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnzo55CNrkLn-j29VLpFWSPaLPlKHuzIc',
    appId: '1:467044849667:android:900bba6acd06819ac61636',
    messagingSenderId: '467044849667',
    projectId: 'kagong-release',
    storageBucket: 'kagong-release.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoNc22hJ7JNda2BM6Df0FQrPZTG7kUW3I',
    appId: '1:467044849667:ios:53e6ad47bd24267ac61636',
    messagingSenderId: '467044849667',
    projectId: 'kagong-release',
    storageBucket: 'kagong-release.firebasestorage.app',
    iosBundleId: 'com.yjh.kagong.kagongMap',
  );

}