// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'core/config/env_keys.dart';

/// Dev [FirebaseOptions] — all values injected via `--dart-define-from-file`.
class DevFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DevFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: EnvKeys.firebaseWebApiKey,
    appId: EnvKeys.firebaseWebAppId,
    messagingSenderId: EnvKeys.firebaseWebMessagingSenderId,
    projectId: EnvKeys.firebaseWebProjectId,
    authDomain: EnvKeys.firebaseWebAuthDomain,
    storageBucket: EnvKeys.firebaseWebStorageBucket,
    measurementId: EnvKeys.firebaseWebMeasurementId,
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: EnvKeys.firebaseAndroidApiKey,
    appId: EnvKeys.firebaseAndroidAppId,
    messagingSenderId: EnvKeys.firebaseAndroidMessagingSenderId,
    projectId: EnvKeys.firebaseAndroidProjectId,
    storageBucket: EnvKeys.firebaseAndroidStorageBucket,
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: EnvKeys.firebaseIosApiKey,
    appId: EnvKeys.firebaseIosAppId,
    messagingSenderId: EnvKeys.firebaseIosMessagingSenderId,
    projectId: EnvKeys.firebaseIosProjectId,
    storageBucket: EnvKeys.firebaseIosStorageBucket,
    androidClientId: EnvKeys.firebaseIosAndroidClientId,
    iosClientId: EnvKeys.firebaseIosIosClientId,
    iosBundleId: EnvKeys.firebaseIosBundleId,
  );
}
