// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'core/config/env_keys.dart';

/// Prod [FirebaseOptions] — all values injected via `--dart-define-from-file`.
///
/// Since `--dart-define-from-file` injects environment-specific values at
/// compile time, both Dev and Prod classes read from the same [EnvKeys].
/// The actual values differ based on which `.env.{dev|prod}` file is supplied.
class ProdFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: EnvKeys.firebaseWebApiKey,
    appId: EnvKeys.firebaseWebAppId,
    messagingSenderId: EnvKeys.firebaseWebMessagingSenderId,
    projectId: EnvKeys.firebaseWebProjectId,
    authDomain: EnvKeys.firebaseWebAuthDomain,
    storageBucket: EnvKeys.firebaseWebStorageBucket,
    measurementId: EnvKeys.firebaseWebMeasurementId,
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: EnvKeys.firebaseAndroidApiKey,
    appId: EnvKeys.firebaseAndroidAppId,
    messagingSenderId: EnvKeys.firebaseAndroidMessagingSenderId,
    projectId: EnvKeys.firebaseAndroidProjectId,
    storageBucket: EnvKeys.firebaseAndroidStorageBucket,
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: EnvKeys.firebaseIosApiKey,
    appId: EnvKeys.firebaseIosAppId,
    messagingSenderId: EnvKeys.firebaseIosMessagingSenderId,
    projectId: EnvKeys.firebaseIosProjectId,
    storageBucket: EnvKeys.firebaseIosStorageBucket,
    iosBundleId: EnvKeys.firebaseIosBundleId,
  );
}
