// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcZ8zcuR_7M5H-Hh4nKEntV0aaf7L-9gM',
    appId: '1:425690840012:web:2e7e6745c0d0cc088b3b69',
    messagingSenderId: '425690840012',
    projectId: 'kagong-map',
    authDomain: 'kagong-map.firebaseapp.com',
    storageBucket: 'kagong-map.firebasestorage.app',
    measurementId: 'G-6Z8RWGJGSE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVgVvr5cuPdtxPF9UIQaYR6fvH5Xynmao',
    appId: '1:425690840012:android:51b9120b72ae2cc88b3b69',
    messagingSenderId: '425690840012',
    projectId: 'kagong-map',
    storageBucket: 'kagong-map.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACGY-MUecqDK7b6BEH1w9ggw4QU7jljYM',
    appId: '1:425690840012:ios:0dc834466750ea368b3b69',
    messagingSenderId: '425690840012',
    projectId: 'kagong-map',
    storageBucket: 'kagong-map.firebasestorage.app',
    iosBundleId: 'com.yjh.kagong.kagongMap',
  );

}